POST http://localhost:3000/event/create
Content-Type: application/json

{
    "name": "Code Challenge Nasa Space Hack",
    "description": "Three days of lectures and challenges",
    "price": 105,
    "location": "Austin, Texas",
    "date": "01/05/2022",
    "url": "http://nasa.com"
}


###
GET http://localhost:3000/event/all

###
GET http://localhost:3000/event/find/613801ff24ab6310d93c2e7b

###
PUT http://localhost:3000/event/update/6138079ba231ddd51b108e4c
Content-Type: application/json

{
    "name": "Hackathon Google Robotics",
    "description": "Code challenges for geeks",
    "price": 50,
    "location": "Sao Paulo, Brazil",
    "date": "02/11/2021",
    "url": "http://google.com"
}

###
DELETE http://localhost:3000/event/delete/6138079ba231ddd51b108e4c